### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by zhmz90** [QData/DeepMotif#1]
Hi, when will you release your code? I am very interested with this paper. 

Thanks.

**Comment by mcolic** [comment]
Yes me too. And while reading I was wondering if those 128 filters come from using one-hot encoding on A,C,G,T?

**Comment by jacklanchantin** [comment]
Hi all,

We are planning on releasing the code after this summer. However, feel free to let me know if you have any further questions before we do release it.

@mcolic, yes they do come from one-hot encoded vectors of A,C,G,T

**Comment by sun9700** [comment]
What's your deep learning framework? Caffe or tensorflow?
Will you release the code of Deep GDashboard?

**Comment by jacklanchantin** [comment]
@zhmz90 @mcolic @sun9700 

Hi all,

Sorry for the late response, but the code is up and running now. Hopefully it is of use to you all.


Jack
